name: ğŸ” GÃ©rer les issues via commit

on:
  push:

jobs:
  manage-issues:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
        
    - name: Run manage-issues action
      uses: theobernardon/theo-flutter/actions/manage-issues@main
      with:
        project-name: "CI/CD Workflow" # ğŸ” Remplace par le nom exact de ton projet GitHub
        column-open: "In Progress"
        column-test: "In Test"
        column-close: "Done"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}